export const CHANGE_SCREEN = 'CHANGE_SCREEN';
// export const CHANGE_SCREEN_TO_POKEMON = 'CHANGE_SCREEN_TO_POKEMON';
// export const CHANGE_SCREEN_TO_STREAMERS = 'CHANGE_SCREEN_TO_STREAMERS';
// export const CHANGE_SCREEN_TO_CREATURES = 'CHANGE_SCREEN_TO_CREATURES';
// export const CHANGE_SCREEN_TO_SUB_BADGES = 'CHANGE_SCREEN_TO_SUB_BADGES';

export const CHANGE_DEVICE_TO_SMALL_PHONE = 'CHANGE_DEVICE_TO_SMALL_PHONE';
export const CHANGE_DEVICE_TO_MEDIUM_PHONE = 'CHANGE_DEVICE_TO_MEDIUM_PHONE';
export const CHANGE_DEVICE_TO_LARGE_PHONE = 'CHANGE_DEVICE_TO_LARGE_PHONE';
export const CHANGE_DEVICE_TO_TABLET = 'CHANGE_DEVICE_TO_TABLET';
export const CHANGE_DEVICE_TO_DESKTOP = 'CHANGE_DEVICE_TO_DESKTOP';
